controller_manager:
  ros__parameters:
  
    update_rate: 1000  # Hz

    robot_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gpio_controller:
      type: melfa_assista_hardware/GPIOController

robot_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      
    state_publish_rate: 200.0
    action_monitor_rate: 20.0

gpio_controller:
  ros__parameters:
    inputs:
      - tool_flansch/coact
    outputs:
      - tool_flansch/coact
  