# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    robot_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_action_controller_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

robot_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      []
    state_interfaces:
      []
gripper_action_controller_controller:
  ros__parameters:
    joint: joint_hand_left